package com.iiqe.study;

import android.app.*;
import android.os.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

public final class MainActivity extends Activity {
    private static final String P1="P1", P3="P3";
    private QuestionRepository bank; private StudyDb db; private LinearLayout body; private Session session;
    private final Handler handler=new Handler(); private int coral,ink,muted,paper,surface,tint,line,success,danger; private Calendar historyMonth;

    @Override public void onCreate(Bundle state){super.onCreate(state);colors();db=new StudyDb(this);historyMonth=Calendar.getInstance();try{bank=new QuestionRepository(this);showHome();}catch(Exception e){new AlertDialog.Builder(this).setTitle("题库无法读取").setMessage(e.getMessage()).setPositiveButton("关闭",null).show();}}
    private void colors(){coral=Color.rgb(184,59,53);ink=Color.rgb(31,36,40);muted=Color.rgb(103,113,121);paper=Color.rgb(255,249,245);surface=Color.WHITE;tint=Color.rgb(248,238,232);line=Color.rgb(229,217,209);success=Color.rgb(45,114,86);danger=Color.rgb(168,47,61);}
    private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} private TextView text(String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setLineSpacing(dp(3),1f);return v;} private GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private Button button(String label,int color,View.OnClickListener click){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextSize(15);b.setTextColor(color==coral?Color.WHITE:ink);b.setMinHeight(dp(46));b.setMinimumHeight(dp(46));b.setBackground(bg(color,8));b.setPadding(dp(10),0,dp(10),0);b.setOnClickListener(click);return b;}
    private void add(View v){body.addView(v);} private void add(View v,LinearLayout.LayoutParams p){body.addView(v,p);} private void gap(int n){Space s=new Space(this);body.addView(s,new LinearLayout.LayoutParams(1,dp(n)));}
    private void shell(String title,String active){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(paper);root.setPadding(dp(20),dp(16),dp(20),dp(10));TextView h=text(title,25,ink);h.setTypeface(null,1);root.addView(h);Space space=new Space(this);root.addView(space,new LinearLayout.LayoutParams(1,dp(12)));ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);String[] labels={"练习","错题","记录","设置"};for(String label:labels){int c=label.equals(active)?coral:tint;Button b=button(label,c,v->navigate(label));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(46),1);p.setMargins(dp(3),dp(8),dp(3),0);nav.addView(b,p);}root.addView(nav);setContentView(root);}
    private void navigate(String destination){pauseTimer();if(session!=null)session.paused=true;if(destination.equals("练习"))showHome();else if(destination.equals("错题"))showErrors();else if(destination.equals("记录"))showHistory();else showSettings();}

    private void showHome(){shell("IIQE 练习","练习");add(text("今天，先把一小段走完。",16,muted));gap(16);LinearLayout rings=new LinearLayout(this);rings.setGravity(Gravity.CENTER);rings.addView(progressBlock(P1,"Paper I"),new LinearLayout.LayoutParams(0,dp(126),1));rings.addView(progressBlock(P3,"Paper III"),new LinearLayout.LayoutParams(0,dp(126),1));add(rings);gap(12);paperCard(P1,"Paper I","保险原理与实务",ExamRules.PAPER_1_QUESTIONS,ExamRules.PAPER_1_MINUTES);gap(12);paperCard(P3,"Paper III","长期保险",ExamRules.PAPER_3_QUESTIONS,ExamRules.PAPER_3_MINUTES);}
    private LinearLayout progressBlock(String paperId,String label){LinearLayout box=new LinearLayout(this);box.setGravity(Gravity.CENTER);box.setOrientation(LinearLayout.VERTICAL);int target=db.getNewCount(paperId)+db.getReviewCount(paperId);ProgressRing ring=new ProgressRing(this,db.todayCount(paperId),target,coral);box.addView(ring,new LinearLayout.LayoutParams(dp(86),dp(86),0));TextView caption=text(label+" 今日",13,muted);caption.setGravity(Gravity.CENTER);box.addView(caption);return box;}
    private void paperCard(String paperId,String label,String name,int examCount,int minutes){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(18),dp(18),dp(18),dp(18));card.setBackground(bg(surface,12));TextView title=text(label+"  "+name,20,ink);title.setTypeface(null,1);card.addView(title);gapIn(card,5);card.addView(text("题库 "+bank.all(paperId).size()+" 题  |  模拟考 "+examCount+" 题 / "+minutes+" 分钟",14,muted));gapIn(card,14);LinearLayout actions=new LinearLayout(this);boolean resumable=session!=null&&session.paper.equals(paperId);Button daily=button(resumable?"继续练习":"每日练习",coral,v->{if(resumable)resumeSession();else startDaily(paperId);});Button exam=button("模拟考试",tint,v->{if(resumable){Toast.makeText(this,"请先继续或完成当前练习。",Toast.LENGTH_SHORT).show();}else startMock(paperId);});actions.addView(daily,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(0,dp(48),1);ep.setMargins(dp(8),0,0,0);actions.addView(exam,ep);card.addView(actions);gapIn(card,12);card.addView(text("今日已练 "+db.todayCount(paperId)+" 题  |  错题 "+db.errorCount(paperId)+" 题",13,muted));add(card);}
    private void startDaily(String paperId){ArrayList<QuestionRepository.Question> list=new ArrayList<>();list.addAll(bank.fromIds(paperId,db.reviewIds(paperId,db.getReviewCount(paperId))));int start=db.getNextIndex(paperId);int newCount=Math.min(db.getNewCount(paperId),Math.max(0,bank.all(paperId).size()-start));for(int i=0;i<newCount;i++)list.add(bank.all(paperId).get(start+i));if(list.isEmpty()){Toast.makeText(this,"该卷已完成；可练错题或开始模拟考试。",Toast.LENGTH_LONG).show();return;}db.advanceNew(paperId,start+newCount);startSession(paperId,"每日练习",list,0);}
    private void startMock(String paperId){int count=paperId.equals(P1)?ExamRules.PAPER_1_QUESTIONS:ExamRules.PAPER_3_QUESTIONS;int minutes=paperId.equals(P1)?ExamRules.PAPER_1_MINUTES:ExamRules.PAPER_3_MINUTES;startSession(paperId,"模拟考试",bank.random(paperId,count),minutes*60);}
    private void startErrors(String paperId){List<QuestionRepository.Question> list=bank.fromIds(paperId,db.errorIds(paperId,200));if(list.isEmpty()){Toast.makeText(this,"这里还没有错题。",Toast.LENGTH_SHORT).show();return;}startSession(paperId,"错题回顾",list,0);}
    private void startSession(String paperId,String mode,List<QuestionRepository.Question> questions,int seconds){pauseTimer();session=new Session(paperId,mode,questions,seconds);showQuestion();}
    private void resumeSession(){if(session==null)return;session.paused=false;showQuestion();}
    private void pauseToHome(){pauseTimer();if(session!=null)session.paused=true;showHome();}
    private void pauseTimer(){handler.removeCallbacksAndMessages(null);}

    private void showQuestion(){if(session==null){showHome();return;}pauseTimer();QuestionRepository.Question q=session.questions.get(session.position);shell(session.mode+"  "+(session.position+1)+" / "+session.questions.size(),"练习");LinearLayout meta=new LinearLayout(this);if(session.remaining>0){TextView clock=text("剩余 "+format(session.remaining),15,coral);clock.setTypeface(null,1);meta.addView(clock,new LinearLayout.LayoutParams(0,dp(44),1));scheduleClock(clock);}else meta.addView(text("已暂停可随时继续",14,muted),new LinearLayout.LayoutParams(0,dp(44),1));Button pause=button("暂停",tint,v->pauseToHome());meta.addView(pause,new LinearLayout.LayoutParams(dp(82),dp(44)));add(meta);gap(12);add(text(q.stem,19,ink));gap(18);String[] labels={"A","B","C","D"};for(int i=0;i<4;i++){String choice=labels[i];Button option=button(choice+". "+q.choices[i],surface,null);option.setTextColor(ink);option.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);option.setPadding(dp(16),0,dp(12),0);if(session.answered){option.setEnabled(false);if(choice.equals(session.chosen))option.setBackground(bg(session.lastCorrect?success:danger,8));if(!session.lastCorrect&&choice.equals(q.answer))option.setBackground(bg(success,8));if(choice.equals(session.chosen)||(!session.lastCorrect&&choice.equals(q.answer)))option.setTextColor(Color.WHITE);}else option.setOnClickListener(v->answer(q,choice));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(60));p.setMargins(0,0,0,dp(8));add(option,p);}if(session.answered){gap(4);TextView feedback=text(session.lastCorrect?"答对了。":"正确答案："+q.answer,16,session.lastCorrect?success:danger);feedback.setTypeface(null,1);add(feedback);gap(12);Button next=button(session.position+1==session.questions.size()?"查看结果":"下一题",coral,v->nextQuestion());add(next,new LinearLayout.LayoutParams(-1,dp(50)));}}
    private void scheduleClock(final TextView clock){handler.postDelayed(new Runnable(){public void run(){if(session==null||session.paused)return;session.remaining--;if(session.remaining<=0){finishSession();return;}clock.setText("剩余 "+format(session.remaining));handler.postDelayed(this,1000);}},1000);}
    private void answer(QuestionRepository.Question q,String choice){if(session==null||session.answered)return;session.answered=true;session.chosen=choice;session.lastCorrect=q.answer.equals(choice);db.record(session.paper,q.id,session.lastCorrect);if(session.lastCorrect)session.correct++;else session.wrongIds.add(q.id);showQuestion();}
    private void nextQuestion(){if(session==null)return;if(++session.position>=session.questions.size()){finishSession();return;}session.answered=false;session.chosen=null;showQuestion();}
    private void finishSession(){if(session==null)return;pauseTimer();Session done=session;session=null;int spent=done.initialSeconds>0?done.initialSeconds-done.remaining:0;db.saveAttempt(done.paper,done.mode,done.questions.size(),done.correct,spent);shell("本次结果","练习");int pct=Math.round(done.correct*100f/done.questions.size());TextView score=text(done.correct+" / "+done.questions.size(),36,ink);score.setTypeface(null,1);add(score);gap(4);String note=done.mode.equals("模拟考试")?(pct>=ExamRules.PASS_PERCENT?"达到模拟及格线 "+ExamRules.PASS_PERCENT+"%":"距离模拟及格线还差 "+(ExamRules.PASS_PERCENT-pct)+"%"):"正确率 "+pct+"%";add(text(note,16,pct>=ExamRules.PASS_PERCENT?success:muted));gap(22);if(!done.wrongIds.isEmpty()){Button review=button("回顾本次错题",tint,v->startSession(done.paper,"本次错题",bank.fromIds(done.paper,done.wrongIds),0));add(review,new LinearLayout.LayoutParams(-1,dp(50)));gap(8);}add(button("返回练习",coral,v->showHome()),new LinearLayout.LayoutParams(-1,dp(50)));}

    private void showErrors(){shell("错题回顾","错题");add(text("错题会保留在本机，并在下一天的温习中优先出现。",15,muted));gap(18);errorCard(P1,"Paper I");gap(12);errorCard(P3,"Paper III");}
    private void errorCard(String paperId,String title){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(16),dp(16),dp(16),dp(16));card.setBackground(bg(surface,12));card.addView(text(title+"  |  "+db.errorCount(paperId)+" 道错题",18,ink));gapIn(card,12);card.addView(button("开始错题回顾",coral,v->{if(session!=null)Toast.makeText(this,"请先完成或继续当前练习。",Toast.LENGTH_SHORT).show();else startErrors(paperId);}),new LinearLayout.LayoutParams(-1,dp(48)));add(card);}
    private void showHistory(){shell("做题记录","记录");LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);Button prev=button("上一月",tint,v->{historyMonth.add(Calendar.MONTH,-1);showHistory();});Button next=button("下一月",tint,v->{historyMonth.add(Calendar.MONTH,1);showHistory();});TextView month=text(new SimpleDateFormat("yyyy 年 M 月",Locale.CHINA).format(historyMonth.getTime()),18,ink);month.setGravity(Gravity.CENTER);header.addView(prev,new LinearLayout.LayoutParams(dp(86),dp(44)));header.addView(month,new LinearLayout.LayoutParams(0,dp(44),1));header.addView(next,new LinearLayout.LayoutParams(dp(86),dp(44)));add(header);gap(12);renderCalendar();gap(14);add(text("点选有记录的日期，可查看当天完成的练习和模拟考试。",14,muted));}
    private void renderCalendar(){Map<Integer,Integer> marks=db.attemptDays(historyMonth.get(Calendar.YEAR),historyMonth.get(Calendar.MONTH));GridLayout grid=new GridLayout(this);grid.setColumnCount(7);String[] weekdays={"日","一","二","三","四","五","六"};for(String day:weekdays){TextView h=text(day,13,muted);h.setGravity(Gravity.CENTER);grid.addView(h,new ViewGroup.LayoutParams(0,dp(32)));GridLayout.LayoutParams hp=(GridLayout.LayoutParams)h.getLayoutParams();hp.width=0;hp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);h.setLayoutParams(hp);}Calendar first=(Calendar)historyMonth.clone();first.set(Calendar.DAY_OF_MONTH,1);for(int i=0;i<first.get(Calendar.DAY_OF_WEEK)-1;i++)addCalendarCell(grid,"",false,0);int days=historyMonth.getActualMaximum(Calendar.DAY_OF_MONTH);for(int d=1;d<=days;d++)addCalendarCell(grid,String.valueOf(d),marks.containsKey(d),marks.containsKey(d)?marks.get(d):0);add(grid);}
    private void addCalendarCell(GridLayout grid,String label,boolean marked,int count){Button cell=button(marked?label+"\n"+count+" 题":label,marked?coral:surface,null);cell.setTextColor(marked?Color.WHITE:ink);cell.setTextSize(14);cell.setEnabled(marked);if(marked){final String date=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(dayFor(Integer.parseInt(label)).getTime());cell.setOnClickListener(v->showDayRecords(date));}GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(52);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(2),dp(2),dp(2),dp(2));grid.addView(cell,p);}
    private Calendar dayFor(int day){Calendar c=(Calendar)historyMonth.clone();c.set(Calendar.DAY_OF_MONTH,day);return c;}
    private void showDayRecords(String date){List<String> rows=db.attemptsOn(date);new AlertDialog.Builder(this).setTitle(date+" 的记录").setItems(rows.toArray(new String[0]),null).setPositiveButton("关闭",null).show();}
    private void showSettings(){shell("每日计划","设置");add(text("分别设置每卷当天的新题和温习题数量。",16,muted));gap(16);settingsCard(P1,"Paper I");gap(12);settingsCard(P3,"Paper III");}
    private void settingsCard(String paperId,String title){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(16),dp(16),dp(16),dp(16));card.setBackground(bg(surface,12));card.addView(text(title,18,ink));gapIn(card,8);card.addView(button("新题："+db.getNewCount(paperId)+" 题",tint,v->chooseCount(paperId,"new_count","每日新题")),new LinearLayout.LayoutParams(-1,dp(48)));gapIn(card,8);card.addView(button("温习："+db.getReviewCount(paperId)+" 题",tint,v->chooseCount(paperId,"review_count","每日温习")),new LinearLayout.LayoutParams(-1,dp(48)));add(card);}
    private void chooseCount(String paperId,String column,String title){String[] values={"5","10","15","20","25","30","40","50"};new AlertDialog.Builder(this).setTitle(title).setItems(values,(d,w)->{db.setCount(paperId,column,Integer.parseInt(values[w]));showSettings();}).show();}
    private void gapIn(LinearLayout parent,int n){Space s=new Space(this);parent.addView(s,new LinearLayout.LayoutParams(1,dp(n)));} private String format(int seconds){return String.format(Locale.US,"%02d:%02d",seconds/60,seconds%60);} @Override public void onBackPressed(){if(session!=null){pauseToHome();}else showHome();}
    private static final class Session {final String paper,mode;final List<QuestionRepository.Question> questions;final int initialSeconds;int remaining,position,correct;boolean answered,paused;String chosen;boolean lastCorrect;final ArrayList<Integer> wrongIds=new ArrayList<>();Session(String p,String m,List<QuestionRepository.Question> q,int sec){paper=p;mode=m;questions=q;initialSeconds=sec;remaining=sec;}}
}
