package com.iiqe.study;

import android.app.*;
import android.os.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import java.util.*;

public final class MainActivity extends Activity {
    private static final String P1="P1", P3="P3";
    private QuestionRepository bank; private StudyDb db; private LinearLayout body; private String activePaper=P1;
    private int coral, ink, muted, paper, surface, tint, line, success, danger;
    private Session session; private final Handler handler=new Handler(); private Runnable ticker;

    @Override public void onCreate(Bundle state) { super.onCreate(state); colors(); db=new StudyDb(this); try { bank=new QuestionRepository(this); showHome(); } catch(Exception e) { new AlertDialog.Builder(this).setTitle("题库无法读取").setMessage(e.getMessage()).setPositiveButton("关闭",null).show(); } }
    private void colors(){ coral=Color.rgb(184,59,53);ink=Color.rgb(31,36,40);muted=Color.rgb(103,113,121);paper=Color.rgb(255,249,245);surface=Color.WHITE;tint=Color.rgb(248,238,232);line=Color.rgb(229,217,209);success=Color.rgb(45,114,86);danger=Color.rgb(168,47,61); }
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} private TextView text(String value,int size,int color){TextView v=new TextView(this);v.setText(value);v.setTextSize(size);v.setTextColor(color);v.setLineSpacing(dp(3),1f);v.setPadding(0,0,0,0);return v;}
    private GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private Button button(String label, int color, View.OnClickListener click){Button b=new Button(this);b.setText(label);b.setTextSize(15);b.setTextColor(color==coral?Color.WHITE:ink);b.setAllCaps(false);b.setMinHeight(dp(48));b.setBackground(bg(color,8));b.setPadding(dp(12),0,dp(12),0);b.setOnClickListener(click);return b;}
    private Button button(String label, int color, View.OnClickListener click, LinearLayout.LayoutParams ignored){return button(label,color,click);}
    private void add(View v){body.addView(v);} private void add(View v, LinearLayout.LayoutParams p){body.addView(v,p);} private void gap(int n){Space s=new Space(this);body.addView(s,new LinearLayout.LayoutParams(1,dp(n)));}
    private void shell(String title){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(paper);root.setPadding(dp(20),dp(18),dp(20),dp(10));
        TextView heading=text(title,25,ink);heading.setTypeface(null,1);root.addView(heading);Space top=new Space(this);root.addView(top,new LinearLayout.LayoutParams(1,dp(14)));
        ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);String[] labels={"练习","错题","记录","设置"};for(String label:labels){Button b=button(label,label.equals("练习")?coral:tint,v->{if(label.equals("练习"))showHome();else if(label.equals("错题"))showErrors();else if(label.equals("记录"))showHistory();else showSettings();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(46),1);p.setMargins(dp(3),dp(10),dp(3),0);nav.addView(b,p);}root.addView(nav);setContentView(root);}
    private void showHome(){shell("IIQE 练习");add(text("今天，先把一小段走完。",16,muted));gap(18);paperCard(P1,"Paper I","保险原理与实务",ExamRules.PAPER_1_QUESTIONS,ExamRules.PAPER_1_MINUTES);gap(12);paperCard(P3,"Paper III","长期保险",ExamRules.PAPER_3_QUESTIONS,ExamRules.PAPER_3_MINUTES);}
    private void paperCard(String paperId,String label,String name,int examCount,int minutes){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(18),dp(18),dp(18),dp(18));card.setBackground(bg(surface,12));
        TextView title=text(label+"  "+name,20,ink);title.setTypeface(null,1);card.addView(title);Space s=new Space(this);card.addView(s,new LinearLayout.LayoutParams(1,dp(5)));card.addView(text("题库 "+bank.all(paperId).size()+" 题  |  模拟考 "+examCount+" 题 / "+minutes+" 分钟",14,muted));Space p=new Space(this);card.addView(p,new LinearLayout.LayoutParams(1,dp(14)));
        LinearLayout actions=new LinearLayout(this);Button a=button("全部过一遍",coral,v->{activePaper=paperId;startDaily(paperId);});Button b=button("模拟考试",tint,v->{activePaper=paperId;startMock(paperId);});actions.addView(a,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(48),1);bp.setMargins(dp(8),0,0,0);actions.addView(b,bp);card.addView(actions);Space q=new Space(this);card.addView(q,new LinearLayout.LayoutParams(1,dp(12)));card.addView(text("今日已练 "+db.todayCount(paperId)+" 题  |  错题 "+db.errorCount(paperId)+" 题",13,muted));add(card);}
    private void startDaily(String paper){ArrayList<QuestionRepository.Question> list=new ArrayList<>();List<Integer> review=db.reviewIds(paper,db.getReviewCount(paper));list.addAll(bank.fromIds(paper,review));int start=db.getNextIndex(paper);int count=Math.min(db.getNewCount(paper),Math.max(0,bank.all(paper).size()-start));for(int i=0;i<count;i++)list.add(bank.all(paper).get(start+i));db.advanceNew(paper,start+count);if(list.isEmpty()){Toast.makeText(this,"该卷已全部完成，可开始模拟考或错题回顾。",Toast.LENGTH_LONG).show();showHome();return;}startSession(paper,"每日练习",list,0);}
    private void startMock(String paper){int count=paper.equals(P1)?ExamRules.PAPER_1_QUESTIONS:ExamRules.PAPER_3_QUESTIONS;int minutes=paper.equals(P1)?ExamRules.PAPER_1_MINUTES:ExamRules.PAPER_3_MINUTES;startSession(paper,"模拟考试",bank.random(paper,count),minutes*60);}
    private void startErrors(String paper){List<QuestionRepository.Question> qs=bank.fromIds(paper,db.errorIds(paper,200));if(qs.isEmpty()){Toast.makeText(this,"这里还没有错题。",Toast.LENGTH_SHORT).show();return;}startSession(paper,"错题回顾",qs,0);}
    private void startSession(String paperId,String mode,List<QuestionRepository.Question> questions,int seconds){handler.removeCallbacksAndMessages(null);session=new Session(paperId,mode,questions,seconds);showQuestion();}
    private void showQuestion(){handler.removeCallbacksAndMessages(null);QuestionRepository.Question q=session.questions.get(session.position);shell(session.mode+"  "+(session.position+1)+" / "+session.questions.size());if(session.remaining>0){final TextView clock=text("剩余 "+format(session.remaining),15,coral);clock.setTypeface(null,1);add(clock);gap(12);ticker=new Runnable(){public void run(){if(session==null)return;session.remaining--;if(session.remaining<=0){finishSession();return;}clock.setText("剩余 "+format(session.remaining));handler.postDelayed(this,1000);}};handler.postDelayed(ticker,1000);}add(text(q.stem,19,ink));gap(18);String[] letters={"A","B","C","D"};for(int i=0;i<4;i++){int x=i;Button option=button(letters[i]+". "+q.choices[i],surface,null);option.setOnClickListener(v->answer(q,letters[x],(Button)v));option.setTextColor(ink);option.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);option.setPadding(dp(16),0,dp(12),0);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(58));p.setMargins(0,0,0,dp(8));add(option,p);} }
    private void answer(QuestionRepository.Question q,String chosen,Button selected){if(session.answered)return;session.answered=true;boolean ok=q.answer.equals(chosen);db.record(session.paper,q.id,ok);if(ok)session.correct++;else session.wrongIds.add(q.id);selected.setBackground(bg(ok?success:danger,8));selected.setTextColor(Color.WHITE);gap(8);TextView feedback=text(ok?"答对了。":"正确答案："+q.answer,16,ok?success:danger);feedback.setTypeface(null,1);add(feedback);gap(12);Button next=button(session.position+1==session.questions.size()?"查看结果":"下一题",coral,v->{if(++session.position>=session.questions.size())finishSession();else showQuestion();});add(next,new LinearLayout.LayoutParams(-1,dp(50)));}
    private void finishSession(){handler.removeCallbacksAndMessages(null);int spent=session.initialSeconds>0?session.initialSeconds-session.remaining:0;db.saveAttempt(session.paper,session.mode,session.questions.size(),session.correct,spent);shell("本次结果");int pct=Math.round(session.correct*100f/session.questions.size());TextView score=text(session.correct+" / "+session.questions.size(),36,ink);score.setTypeface(null,1);add(score);gap(4);String note=session.mode.equals("模拟考试")?(pct>=ExamRules.PASS_PERCENT?"达到模拟及格线 "+ExamRules.PASS_PERCENT+"%":"距离模拟及格线还差 "+(ExamRules.PASS_PERCENT-pct)+"%"):("正确率 "+pct+"%");add(text(note,16,pct>=ExamRules.PASS_PERCENT?success:muted));gap(22);if(!session.wrongIds.isEmpty())add(button("回顾本次错题",tint,v->{List<QuestionRepository.Question> qs=bank.fromIds(session.paper,session.wrongIds);startSession(session.paper,"本次错题",qs,0);},new LinearLayout.LayoutParams(-1,dp(50))));gap(8);add(button("返回练习",coral,v->showHome()),new LinearLayout.LayoutParams(-1,dp(50)));session=null;}
    private void showErrors(){shell("错题回顾");add(text("每次答错都会留在本机。重新答对不会抹掉记录，但会帮助你看见改善。",15,muted));gap(18);errorCard(P1,"Paper I");gap(12);errorCard(P3,"Paper III");}
    private void errorCard(String paperId,String title){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(16),dp(16),dp(16));c.setBackground(bg(surface,12));c.addView(text(title+"  |  "+db.errorCount(paperId)+" 道错题",18,ink));Space s=new Space(this);c.addView(s,new LinearLayout.LayoutParams(1,dp(12)));c.addView(button("开始错题回顾",coral,v->{activePaper=paperId;startErrors(paperId);}),new LinearLayout.LayoutParams(-1,dp(48)));add(c);}
    private void showHistory(){shell("做题记录");List<String> items=db.history();if(items.isEmpty()){add(text("完成一次每日练习或模拟考试后，成绩会在这里出现。",16,muted));return;}for(String item:items){TextView row=text(item,16,ink);row.setPadding(dp(14),dp(14),dp(14),dp(14));row.setBackground(bg(surface,8));add(row);gap(8);}}
    private void showSettings(){shell("每日计划");add(text("分别设置每张试卷每天的新题和温习题数量。",16,muted));gap(16);settingsCard(P1,"Paper I");gap(12);settingsCard(P3,"Paper III");}
    private void settingsCard(String paperId,String title){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(16),dp(16),dp(16));c.setBackground(bg(surface,12));c.addView(text(title,18,ink));gapIn(c,8);Button a=button("新题："+db.getNewCount(paperId)+" 题",tint,v->chooseCount(paperId,"new_count","每日新题"));Button b=button("温习："+db.getReviewCount(paperId)+" 题",tint,v->chooseCount(paperId,"review_count","每日温习"));c.addView(a,new LinearLayout.LayoutParams(-1,dp(48)));gapIn(c,8);c.addView(b,new LinearLayout.LayoutParams(-1,dp(48)));add(c);}
    private void gapIn(LinearLayout parent,int n){Space s=new Space(this);parent.addView(s,new LinearLayout.LayoutParams(1,dp(n)));}
    private void chooseCount(String paperId,String column,String title){String[] values={"5","10","15","20","25","30","40","50"};new AlertDialog.Builder(this).setTitle(title).setItems(values,(d,w)->{db.setCount(paperId,column,Integer.parseInt(values[w]));showSettings();}).show();}
    private String format(int seconds){return String.format(Locale.US,"%02d:%02d",seconds/60,seconds%60);} @Override public void onBackPressed(){handler.removeCallbacksAndMessages(null);showHome();}
    private static final class Session { final String paper,mode; final List<QuestionRepository.Question> questions; final int initialSeconds; int remaining,position,correct; boolean answered; final ArrayList<Integer> wrongIds=new ArrayList<>(); Session(String p,String m,List<QuestionRepository.Question>q,int sec){paper=p;mode=m;questions=q;initialSeconds=sec;remaining=sec;} }
}
